### ISSUE TITLE
gulp watch fail to install theme bundle if you have liferay-hook.xml in WEB-INF

### ISSUE THREAD

**Issue by backtime** [liferay/liferay-js-themes-toolkit#120]
Having liferay-hook.xml file in your theme cause watch to fail install bundle.

The command 
`install 'webbundledir:file://.../.web_bundle_build?Web-ContextPath=/my-theme'`
fail with NullPointerException 

The Liferay log:
```
2018-12-08 22:53:09.218 ERROR [pipe-install 'webbundledir:file:///.../.web_bundle_build?Web-ContextPath=/my-theme'][WabDirURLStreamHandlerService:140] Unable to open connection
java.lang.RuntimeException: com.liferay.portal.kernel.deploy.auto.AutoDeployException: More than one auto deploy listener is available for .../.web_bundle_build: com.liferay.portal.deploy.auto.HookAutoDeployListener, com.liferay.portal.deploy.auto.ThemeAutoDeployListener
	at com.liferay.portal.osgi.web.wab.generator.internal.processor.WabProcessor.getAutoDeployListener(WabProcessor.java:310)
	at com.liferay.portal.osgi.web.wab.generator.internal.processor.WabProcessor.executeAutoDeployers(WabProcessor.java:247)
	at com.liferay.portal.osgi.web.wab.generator.internal.processor.WabProcessor.autoDeploy(WabProcessor.java:156)
	at com.liferay.portal.osgi.web.wab.generator.internal.processor.WabProcessor.getProcessedFile(WabProcessor.java:111)
	at com.liferay.portal.osgi.web.wab.generator.internal.WabGenerator.generate(WabGenerator.java:90)
	at com.liferay.portal.osgi.web.wab.reference.support.internal.WabDirURLStreamHandlerService.openConnection(WabDirURLStreamHandlerService.java:123)
	at org.eclipse.osgi.internal.url.URLStreamHandlerProxy.openConnection(URLStreamHandlerProxy.java:114)
	at java.net.URL.openConnection(URL.java:979)
	at org.eclipse.osgi.internal.location.LocationHelper.getConnection(LocationHelper.java:106)
	at org.eclipse.osgi.storage.Storage.getContentConnection(Storage.java:580)
	at org.eclipse.osgi.storage.Storage.getContentConnection(Storage.java:550)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.installBundle(BundleContextImpl.java:145)
	at org.apache.felix.gogo.command.Basic.install(Basic.java:437)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.felix.gogo.runtime.Reflective.invoke(Reflective.java:139)
	at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:91)
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:599)
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:526)
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:415)
	at org.apache.felix.gogo.runtime.Pipe.doCall(Pipe.java:416)
	at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:229)
	at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:59)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.liferay.portal.kernel.deploy.auto.AutoDeployException: More than one auto deploy listener is available for .../.web_bundle_build: com.liferay.portal.deploy.auto.HookAutoDeployListener, com.liferay.portal.deploy.auto.ThemeAutoDeployListener
```

**Comment by wincent** [comment]
We have significantly changed the watch implementation in #190 with the hope of fixing the existing issues. At the time of writing, that's in the "master" branch and will be included in the next release (v8.0.0-rc.4). The master issue for tracking the rewrite is #127, so I am going to close these separate tickets and ask that we consolidate further discussion about watch there.
