### ISSUE TITLE
gulp build is not supported for themes with version '6.2'

### ISSUE THREAD

**Issue by john-co** [liferay/liferay-js-themes-toolkit#244]
Steps to reproduce:
`npm install -g generator-liferay-theme@^8.x.x`
`npm install -g liferay-theme-tasks@^8.x.x`
`yo liferay-theme:import` on a 6.2 theme (zoe-healthcare)
`gulp build` on imported theme

/home/john-co/zoe-healthcare-theme/node_modules/liferay-theme-tasks/lib/doctor.js:84
					throw new Error(
					^

Error: Task 'build' is not supported for themes with version '6.2' in this version of 'liferay-theme-tasks'
    at assertTasksSupported (/home/john-co/zoe-healthcare-theme/node_modules/liferay-theme-tasks/lib/doctor.js:84:12)
    at doctor (/home/john-co/zoe-healthcare-theme/node_modules/liferay-theme-tasks/lib/doctor.js:32:2)
    at register (/home/john-co/zoe-healthcare-theme/node_modules/liferay-theme-tasks/index.js:62:2)
    at /home/john-co/zoe-healthcare-theme/node_modules/liferay-plugin-node-tasks/index.js:37:4
    at arrayEach (/home/john-co/zoe-healthcare-theme/node_modules/liferay-plugin-node-tasks/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/home/john-co/zoe-healthcare-theme/node_modules/liferay-plugin-node-tasks/node_modules/lodash/lodash.js:9344:14)
    at Object.module.exports.registerTasks (/home/john-co/zoe-healthcare-theme/node_modules/liferay-plugin-node-tasks/index.js:36:5)
    at Object.module.exports.registerTasks (/home/john-co/zoe-healthcare-theme/node_modules/liferay-theme-tasks/index.js:23:21)
    at Object.<anonymous> (/home/john-co/zoe-healthcare-theme/gulpfile.js:12:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Liftoff.handleArguments (/home/linuxbrew/.linuxbrew/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.execute (/home/linuxbrew/.linuxbrew/lib/node_modules/gulp/node_modules/liftoff/index.js:203:12)
    at module.exports (/home/linuxbrew/.linuxbrew/lib/node_modules/gulp/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/home/linuxbrew/.linuxbrew/lib/node_modules/gulp/node_modules/liftoff/index.js:195:5)
    at /home/linuxbrew/.linuxbrew/lib/node_modules/gulp/node_modules/liftoff/index.js:165:9
    at /home/linuxbrew/.linuxbrew/lib/node_modules/gulp/node_modules/v8flags/index.js:110:14
    at /home/linuxbrew/.linuxbrew/lib/node_modules/gulp/node_modules/v8flags/index.js:38:12
    at /home/linuxbrew/.linuxbrew/lib/node_modules/gulp/node_modules/v8flags/index.js:49:7
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by mwilliams2014** [comment]
Hey @john-co , following our docs: https://dev.liferay.com/en/develop/tutorials/-/knowledge_base/7-1/running-the-upgrade-task-for-6-2-themes are you able to run `gulp upgrade` and the run `gulp build` ?

**Comment by john-co** [comment]
when I run `gulp upgrade` on the imported theme, I get the following error:
https://gist.github.com/john-co/e91156f925b5e75266ed021e0a2820a3

**Comment by wincent** [comment]
@john-co: Is there somewhere we could get hold of this theme's files so that we can repro and investigate further? One of the problems I've had with working on the toolkit is that I don't actually have any *real* old-school themes (only the fixtures in the test directories, which are somewhat artificial/fake/synthentic and might not be the highest fidelity replicas of real 6.2 themes).

**Comment by wincent** [comment]
@john-co update: I am able to reproduce the error from your gist using a 6.2 theme I got from @marcoscv-work. Looking for a fix now.

**Comment by wincent** [comment]
8.0.2 is now published to NPM, so closing. Please let us know if you discover any further issues.

**Comment by john-co** [comment]
@mwilliams2014 Looking over our [QA test plan](https://docs.google.com/document/d/1yotZiG6Hog9Vp-72MvWNznoJ1tNDz69YNuisKpKGQn0/edit#heading=h.tr5m0ndj0mf) we ran last summer, I didn't have to run `gulp upgrade` in order for `gulp build` to work.

**Comment by mwilliams2014** [comment]
Ah ok @john-co . Well, hopefully @wincent 's fix solves that as well. Makes sense. Once the theme is imported to use the Liferay JS Toolkit, it should have access to all the gulp tasks as well.

**Comment by wincent** [comment]
Yep, we should probably update the plan to reflect that as a necessary step. I believe what should happen now is:

1. Run `yo liferay-theme:import`.
2. Pass path to theme (now, relative or absolute paths should work).
3. (Optional) Run `gulp build` and see an error that says, `Error: Task 'build' is not supported for themes with version '6.2' in this version of 'liferay-theme-tasks' - please run "gulp upgrade" first`
4. Run `gulp upgrade`
5. Run `gulp build`

I know you filed #255 about what is supposed to happen after `import` completes too; on that one we can discuss whether it's supposed to create a new folder or not (your test plan makes it sound like it should).

**Comment by john-co** [comment]
@wincent I see, so from what I'm understanding `gulp build` for 6.2 themes should never have been possible since liferay-js-themes-toolkitl is meant for 7.0+. This reasoning seems to be in line with documentation on dev.liferay.com (no documentation on how to use js-themes-toolkit solely for 6.2). Thanks for clarifying!

**Comment by jbalsas** [comment]
This is correct. We just supported importing a 6.2 theme generated by the old `plugins-sdk` so you could migrate to 7.x and upwards

**Comment by wincent** [comment]
Yeah, that matches my understanding. I only recently started contributing to this project, but when I look back at the history I can't seen any evidence of it working with 6.2 (other than importing them) for a long-ish time. For example [eb0775bc](https://github.com/liferay/liferay-js-themes-toolkit/commit/eb0775bc9f6e2747a84d1c4220fe4b5d3f9a2a4e) ("Makes 7.1 default and removes theme-deps-6.2 as it won't be supported in 7.1") dates from March 2018, early on in v8 development, and [97db102aa](https://github.com/liferay/liferay-js-themes-toolkit/commit/97db102aa8a76853a16d994c9142dcacebc81678) ("Remove 6.2 support and add 7.1 for themelet generator") goes back to December 2017.
