### ISSUE TITLE
Should be able to pass a relative path to liferay-theme:import generator

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-js-themes-toolkit#245]
Noticed this while attempting to repro: https://github.com/liferay/liferay-js-themes-toolkit/issues/244

I was running the local 8.x version of the generator with:

```
yo ./packages/generator-liferay-theme/generators/import
```

And found that importing a 6.2 theme works if I supply an absolute path at the prompt (eg. `/Users/greghurrell/code/liferay-js-themes-toolkit/manzanita-theme`) but not a relative path (eg. `manzanita-theme` or `./manzanita-theme`). Relevant bits from the stack-trace:

```
AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /Users/greghurrell/code/liferay-js-themes-toolkit/manzanita-theme/manzanita-theme/docroot/_diffs
    at EditionInterface.exports.copy (/Users/greghurrell/code/liferay-js-themes-toolkit/node_modules/mem-fs-editor/lib/actions/copy.js:48:3)
    at module.exports._writeThemeFiles (/Users/greghurrell/code/liferay-js-themes-toolkit/packages/generator-liferay-theme/generators/import/index.js:34:11)
```

(Note the duplicated "manzanita-theme/manzanita-theme" in the path.)

**Comment by wincent** [comment]
8.0.2 is now published to NPM, so closing.
