### ISSUE TITLE
Gulp upgrade task 6.2 to 7.0 TypeError

### ISSUE THREAD

**Issue by fortunatomaldonado** [liferay/liferay-js-themes-toolkit#80]
Node: 6.12.3
npm: 6.2.0

Using gulp upgrade on a 6.2 theme results in TypeError. It seems like the this can be fixed by making sure str is a string. Let me know if any more information is needed. 

```
john@john-Precision-5520:~/Liferay/MyTest-theme$ gulp upgrade
[12:18:31] Warning: You must install the correct dependencies, please run npm i --save-dev from your theme directory.
[12:18:31] Using gulpfile ~/Liferay/MyTest-theme/gulpfile.js
[12:18:31] Starting 'upgrade'...
[12:18:31] Starting 'upgrade:create-backup-files'...
? Would you like to overwrite the existing _backup directory and it's contents? Yes
[12:18:34] Finished 'upgrade:create-backup-files' after 2.48 s
[12:18:34] Starting 'upgrade:black-list'...
[12:18:34] Finished 'upgrade:black-list' after 22 ms
[12:18:34] Starting 'upgrade:replace-compass'...
[12:18:34] Finished 'upgrade:replace-compass' after 45 ms
[12:18:34] Starting 'upgrade:convert-bootstrap'...
Wrote file: src/css/_aui_variables.scss
Wrote file: src/css/application.css
Wrote file: src/css/aui.css
Wrote file: src/css/bootstrap.css
/home/Liferay/MyTest-theme/node_modules/convert-bootstrap-2-to-3/lib/formatters/css.js:61
            if (str.indexOf('content-box') > -1) {
                    ^

TypeError: str.indexOf is not a function
    at constructor._checkPadding (/home/john/Liferay/MyTest-theme/node_modules/convert-bootstrap-2-to-3/lib/formatters/css.js:61:13)
    at constructor._extractRecursive (/home/john/Liferay/MyTest-theme/node_modules/convert-bootstrap-2-to-3/lib/formatters/css.js:247:6)
    at constructor.format (/home/john/Liferay/MyTest-theme/node_modules/convert-bootstrap-2-to-3/lib/formatters/css.js:23:14)
    at CLI.processFileData (/home/john/Liferay/MyTest-theme/node_modules/convert-bootstrap-2-to-3/lib/cli.js:181:28)
    at CLI.formatFile (/home/john/Liferay/MyTest-theme/node_modules/convert-bootstrap-2-to-3/lib/cli.js:80:9)
    at CLI.onRead (/home/john/Liferay/MyTest-theme/node_modules/convert-bootstrap-2-to-3/lib/cli.js:126:9)
    at wrapper (/home/john/Liferay/MyTest-theme/node_modules/convert-bootstrap-2-to-3/node_modules/lodash/index.js:3533:19)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

**Comment by jbalsas** [comment]
Hey @fortunatomaldonado, could you share your theme with us so we can figure out where this is coming from? It might be that execution is not even expected to get there but it is for some reason.

Thanks!

**Comment by alfonsocrisci** [comment]
Hi Chema @jbalsas , I am answering on behalf of the US team as it may take some time for them to catch up due to the time zone and today's US bank holiday. Theme + reproduction steps can be found here: https://issues.liferay.com/browse/LPP-31390 + https://issues.liferay.com/browse/LPP-31390?focusedCommentId=1531369&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1531369

I hope this helps. Thanks !

**Comment by jbalsas** [comment]
Thanks @alfonsocrisci, we'll take a look asap!

**Comment by jbalsas** [comment]
Hey @alfonsocrisci, @fortunatomaldonado, I've tracked this down, and as you suggest internally, this is easilly addressed with a fix in the [convert-bootstrap-2-to-3](https://github.com/natecavanaugh/convert-bootstrap-2-to-3) library. I've filed https://github.com/natecavanaugh/convert-bootstrap-2-to-3/issues/11 to fix it there and release a new version.

Looking at the offending theme, this is caused by the following type of code (I've found only 2 instances):

```
.portlet-column-content {}
```

```
.vv-form-group label {}
```

In the meantime, I'd suggest to simply remove those empty rules and go on with the upgrade.

**Comment by alfonsocrisci** [comment]
Thanks @jbalsas , I just shared this info with the affected users.

**Comment by wincent** [comment]
We've just migrated this project to [the `liferay-frontend-projects` monorepo](https://github.com/liferay/liferay-frontend-projects) in the name of consolidation. As this issue is quite old now, and it has a workaround, I'm not going to transfer it automatically. If you consider it to be still relevant, please [create a fresh issue over in the new repo](https://github.com/liferay/liferay-frontend-projects/issues/new?labels=js-themes-toolkit&template=js-themes-toolkit.md).
